package com.alnoor.modelacademy;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    final int teal=Color.rgb(15,157,154), dark=Color.rgb(7,94,93), bg=Color.rgb(246,250,250); LinearLayout root; FirebaseRest fb; String role=""; JSONObject profile=new JSONObject();
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.DKGRAY);t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}
    GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} LinearLayout.LayoutParams m(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(teal,18));return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);fb=new FirebaseRest(getString(R.string.firebase_api_key),getString(R.string.firebase_database_url));showHome();}
    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(10),dp(10),dp(10));root.setBackgroundColor(bg);setContentView(root);}
    ImageView logo(int h){ImageView i=new ImageView(this);i.setImageResource(R.drawable.school_logo);i.setAdjustViewBounds(true);i.setPadding(dp(20),dp(8),dp(20),dp(8));root.addView(i,new LinearLayout.LayoutParams(-1,dp(h)));return i;}
    void showHome(){base();logo(210);TextView h=text("AL-NOOR MODEL ACADEMY",25);h.setGravity(17);h.setTypeface(null,Typeface.BOLD);h.setTextColor(dark);root.addView(h);TextView q=text("Knowledge for Progress\nRun by Baromasia Al Nur Academy Foundation",15);q.setGravity(17);q.setTextColor(teal);root.addView(q);Button b=btn("LOGIN TO SCHOOL APP");b.setOnClickListener(v->showLogin());root.addView(b,m(20,20,20,10));TextView f=text("School Management • Attendance • Results • Homework • Routine • Notices • Fees",13);f.setGravity(17);root.addView(f);}
    void showLogin(){base();logo(145);TextView h=text("School Login",23);h.setGravity(17);h.setTypeface(null,Typeface.BOLD);root.addView(h);EditText email=new EditText(this);email.setHint("Email");email.setInputType(33);root.addView(email,m(22,8,22,4));EditText pass=new EditText(this);pass.setHint("Password");pass.setInputType(129);root.addView(pass,m(22,4,22,8));Spinner sp=new Spinner(this);String[] roles={"Admin / School Authority","Teacher","Student","Parent"};sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,roles));root.addView(sp,m(22,4,22,8));Button login=btn("LOGIN");root.addView(login,m(22,8,22,8));TextView demo=text(fb.configured()?"Connected mode: Firebase":"Demo mode: add Firebase values in res/values/config.xml");demo.setGravity(17);demo.setTextColor(fb.configured()?dark:Color.rgb(180,100,20));root.addView(demo);Button back=btn("← Back");back.setOnClickListener(v->showHome());root.addView(back,m(22,18,22,4));
        login.setOnClickListener(v->{ if(email.getText().toString().trim().isEmpty()||pass.getText().toString().isEmpty()){toast("Enter email and password");return;} role=roles[sp.getSelectedItemPosition()]; if(!fb.configured()){toast("Demo mode: Firebase is not configured");showDashboard();return;} login.setEnabled(false);fb.login(email.getText().toString().trim(),pass.getText().toString(),(ok,data)->runOnUiThread(()->{login.setEnabled(true);if(!ok){toast("Login failed: "+data);return;}loadProfile();})); }); }
    void loadProfile(){fb.get("users/"+fb.getUid(),(ok,data)->runOnUiThread(()->{try{profile=new JSONObject(ok?data:"{}");String serverRole=profile.optString("role","");if(!serverRole.isEmpty())role=serverRole;showDashboard();}catch(Exception e){showDashboard();}}));}
    String roleName(){if(role.startsWith("Admin"))return "Admin / School Authority";return role;}
    void showDashboard(){base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=text("AL-NOOR MODEL ACADEMY",19);h.setTypeface(null,Typeface.BOLD);h.setTextColor(dark);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));Button out=btn("Logout");out.setTextSize(12);out.setOnClickListener(v->{role="";profile=new JSONObject();showHome();});top.addView(out,new LinearLayout.LayoutParams(dp(90),dp(48)));root.addView(top);TextView w=text("Welcome\n"+profile.optString("name",roleName()),21);w.setTextColor(dark);w.setTypeface(null,Typeface.BOLD);root.addView(w);GridLayout g=new GridLayout(this);g.setColumnCount(2);String[] a={"📢 Notices","📅 Class Routine","📝 Homework","📊 Exam Results","✅ Attendance","💰 Fees","📚 Study Materials","☎️ School Contact"};for(String x:a){Button b=btn(x);b.setTextSize(14);b.setOnClickListener(v->module(x));GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(86);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(6),dp(6),dp(6),dp(6));g.addView(b,p);}root.addView(g,new LinearLayout.LayoutParams(-1,-2));if(roleName().startsWith("Admin")||roleName().equals("Teacher")){Button add=btn("＋ Add Notice");add.setOnClickListener(v->addNotice());root.addView(add,m(18,12,18,4));}TextView ver=text("Online School Management • v2.0");ver.setGravity(17);ver.setTextColor(Color.GRAY);root.addView(ver,m(0,12,0,0));}
    void module(String x){base();Button back=btn("← Dashboard");back.setOnClickListener(v->showDashboard());root.addView(back,m(8,4,8,8));TextView h=text(x,24);h.setTextColor(dark);h.setTypeface(null,Typeface.BOLD);root.addView(h);String path="";if(x.contains("Notices"))path="notices";else if(x.contains("Routine"))path="routine";else if(x.contains("Homework"))path="homework";else if(x.contains("Results"))path="results";else if(x.contains("Attendance"))path="attendance";else if(x.contains("Fees"))path="fees";else if(x.contains("Materials"))path="materials";else {root.addView(text("AL-NOOR MODEL ACADEMY\nContact the school office for assistance."));return;} if(!fb.configured()){root.addView(text("Firebase is not configured yet. Add your Firebase API key and database URL in res/values/config.xml, then rebuild the app."));return;}ProgressBar pb=new ProgressBar(this);root.addView(pb);fb.get(path,(ok,data)->runOnUiThread(()->{root.removeView(pb);if(!ok){root.addView(text("Could not load data."));return;}renderJson(data);}));}
    void renderJson(String data){try{JSONObject j=new JSONObject(data);if(j.length()==0){root.addView(text("No records available yet."));return;}Iterator<String> it=j.keys();while(it.hasNext()){String k=it.next();Object v=j.get(k);TextView t=text("• "+(v instanceof JSONObject?((JSONObject)v).optString("title",k)+"\n"+((JSONObject)v).toString().replace("{"," ").replace("}",""):v.toString()),15);t.setBackground(round(Color.WHITE,14));root.addView(t,m(8,5,8,5));}}catch(Exception e){root.addView(text(data));}}
    void addNotice(){base();Button back=btn("← Dashboard");back.setOnClickListener(v->showDashboard());root.addView(back,m(8,4,8,8));TextView h=text("Create Notice",23);h.setTextColor(dark);h.setTypeface(null,Typeface.BOLD);root.addView(h);EditText title=new EditText(this);title.setHint("Notice title");root.addView(title,m(15,8,15,4));EditText body=new EditText(this);body.setHint("Notice details");body.setMinLines(5);body.setGravity(Gravity.TOP);root.addView(body,m(15,4,15,8));Button save=btn("Publish Notice");root.addView(save,m(15,8,15,8));save.setOnClickListener(v->{if(!fb.configured()){toast("Configure Firebase first");return;}String id="n"+System.currentTimeMillis();JSONObject n=new JSONObject();try{n.put("title",title.getText().toString());n.put("body",body.getText().toString());n.put("createdAt",System.currentTimeMillis());n.put("createdBy",fb.getUid());}catch(Exception e){}save.setEnabled(false);fb.put("notices/"+id,n,(ok,data)->runOnUiThread(()->{save.setEnabled(true);toast(ok?"Notice published":"Publish failed");if(ok)showDashboard();}));});}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
